---
title: "About Craig"
description: |

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**CRAIG KOPULSKY**, a first-year master’s student, graduated from Northwestern University with a Bachelor of Arts in Economics and Psychology in 2012. Craig has 7 years of experience working in market research, consumer insights, and brand strategy consulting. He has worked with major brands and Fortune 500 companies in industries from Entertainment, to Consumer Packaged Goods, to Food and Beverage, to Finance. In 2018, after leaving Los Angeles based brand strategy and innovation firm BrandIQ, Craig cultivated his own client base for his research, analytics, and insights services. Throughout his career, Craig had an interest in finding a new, more fulfilling direction to pursue. In 2017, Craig received his Permaculture Design Certificate from the Permaculture Academy of Los Angeles, an experience that instilled in him a deep interest in natural systems and remediation, ultimately leading him towards his new path. An avid traveler, Craig has had the opportunity to explore many areas throughout South and Southeast Asia. In addition to a deep appreciation for other cultures, these experiences gave him perspectives on how pollution impacts different people and environments around the world. Craig sees a serious need for systems design to permeate throughout all our human activities, closing the loop on our waste streams. Specializing in Pollution Prevention and Remediation and focusing on Eco-Entrepreneurship at the Bren School, Craig seeks to bring economically efficient, ecologically sound remediation solutions to the market.